### ISSUE TITLE
[CT-2017] Column descriptions are also included in the search

### ISSUE THREAD

**Issue by shinyatakimoto** [dbt-labs/dbt-docs#369] opened 2023-02-02 14:12 UTC
### Describe the feature
Words in the column description text are also included in the search.

### Who will this benefit?
Column names are defined in English due to database constraints. However, in countries where English is not the native language, many data users search for data in their native language, and it is often the case that column names defined in English do not match and are not displayed in search results.

Since there is no function to define the name of a column in another expression, we have created a document that includes the column name in the column description text. We hope that this modification will allow people to find appropriate data in the catalog by including the descriptive text of column names in the search results.

Example
column name: shop_name
shop name in Japanese: "店舗名"

**Comment by dbeatty10** [comment] 2023-02-10 04:41
Thanks for reaching out @shinyatakimoto !

It looks like this has been requested multiple times:
- https://github.com/dbt-labs/dbt-docs/issues/140
- https://github.com/dbt-labs/dbt-docs/issues/322

Thanks for sharing the details of your use-case. Reading through the comments across these issues, it was mentioned a couple times is that this would enable multi-language search at the column level.

There's quite a few 👍 between your issue and the others, so I opened up a PR:
- https://github.com/dbt-labs/dbt-docs/pull/371

In the meantime, I'm going to close this particular issue as a duplicate of #322.

**Closed by dbeatty10** 2023-02-10 04:41 UTC
Labels: enhancement, triage
